const SHOP_DATA = [
  {
    title: 'Hats',
    items: [
      {
        id: 1,
        name: 'Brown Brim',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 25,
      },
      {
        id: 2,
        name: 'Blue Beanie',
        imageUrl: 'https://i.ibb.co/ypkgK0X/blue-beanie.png',
        price: 18,
      },
      {
        id: 3,
        name: 'Brown Cowboy',
        imageUrl: 'https://i.ibb.co/QdJwgmp/brown-cowboy.png',
        price: 35,
      },
      {
        id: 4,
        name: 'Grey Brim',
        imageUrl: 'https://i.ibb.co/RjBLWxB/grey-brim.png',
        price: 25,
      },
      {
        id: 5,
        name: 'Green Beanie',
        imageUrl: 'https://i.ibb.co/YTjW3vF/green-beanie.png',
        price: 18,
      },
      {
        id: 6,
        name: 'Palm Tree Cap',
        imageUrl: 'https://i.ibb.co/rKBDvJX/palm-tree-cap.png',
        price: 14,
      },
      {
        id: 7,
        name: 'Red Beanie',
        imageUrl: 'https://i.ibb.co/bLB646Z/red-beanie.png',
        price: 18,
      },
      {
        id: 8,
        name: 'Wolf Cap',
        imageUrl: 'https://i.ibb.co/1f2nWMM/wolf-cap.png',
        price: 14,
      },
      {
        id: 9,
        name: 'Blue Snapback',
        imageUrl: 'https://i.ibb.co/X2VJP2W/blue-snapback.png',
        price: 16,
      },
      {
        id: 101,
        name: 'Black Fedora',
        imageUrl: 'https://placehold.co/400x400/1a1a1a/f5f5f5?text=Black+Fedora',
        price: 32,
      },
      {
        id: 102,
        name: 'Khaki Bucket Hat',
        imageUrl: 'https://placehold.co/400x400/8a7752/ffffff?text=Khaki+Bucket',
        price: 22,
      },
      {
        id: 103,
        name: 'White Dad Cap',
        imageUrl: 'https://placehold.co/400x400/e8e8e8/222222?text=White+Dad+Cap',
        price: 19,
      },
      {
        id: 104,
        name: 'Camo Trucker Hat',
        imageUrl: 'https://placehold.co/400x400/4b5320/ffffff?text=Camo+Trucker',
        price: 21,
      },
      {
        id: 105,
        name: 'Straw Sun Hat',
        imageUrl: 'https://placehold.co/400x400/d2b48c/222222?text=Straw+Sun+Hat',
        price: 28,
        description: 'Wide-brim woven straw hat, perfect for sunny days at the beach or in the city.',
      },
      {
        id: 106,
        name: 'Wool Newsboy Cap',
        imageUrl: 'https://placehold.co/400x400/6b5b4f/ffffff?text=Newsboy+Cap',
        price: 30,
        description: 'Classic wool newsboy cap with a soft lined interior, great for cooler weather.',
      },
      {
        id: 107,
        name: 'Mesh Trucker Cap',
        imageUrl: 'https://placehold.co/400x400/2f4f4f/ffffff?text=Mesh+Trucker',
        price: 18,
        description: 'Breathable mesh-back trucker cap with an adjustable snap closure.',
      },
      {
        id: 108,
        name: 'Wide Brim Panama Hat',
        imageUrl: 'https://placehold.co/400x400/e6d5b8/222222?text=Panama+Hat',
        price: 36,
        description: 'Lightweight Panama-style hat woven from natural fibers, ideal for summer outfits.',
      },
      {
        id: 109,
        name: 'Ribbed Beanie',
        imageUrl: 'https://placehold.co/400x400/303030/ffffff?text=Ribbed+Beanie',
        price: 16,
        description: 'Snug-fit ribbed knit beanie that keeps you warm without sacrificing style.',
      },
    ],
  },
  {
    title: 'Sneakers',
    items: [
      {
        id: 10,
        name: 'Adidas NMD',
        imageUrl: 'https://i.ibb.co/0s3pdnc/adidas-nmd.png',
        price: 220,
      },
      {
        id: 11,
        name: 'Adidas Yeezy',
        imageUrl: 'https://i.ibb.co/dJbG1cT/yeezy.png',
        price: 280,
      },
      {
        id: 12,
        name: 'Black Converse',
        imageUrl: 'https://i.ibb.co/bPmVXyP/black-converse.png',
        price: 110,
      },
      {
        id: 13,
        name: 'Nike White AirForce',
        imageUrl: 'https://i.ibb.co/1RcFPk0/white-nike-high-tops.png',
        price: 160,
      },
      {
        id: 14,
        name: 'Nike Red High Tops',
        imageUrl: 'https://i.ibb.co/QcvzydB/nikes-red.png',
        price: 160,
      },
      {
        id: 15,
        name: 'Nike Brown High Tops',
        imageUrl: 'https://i.ibb.co/fMTV342/nike-brown.png',
        price: 160,
      },
      {
        id: 16,
        name: 'Air Jordan Limited',
        imageUrl: 'https://i.ibb.co/w4k6Ws9/nike-funky.png',
        price: 190,
      },
      {
        id: 17,
        name: 'Timberlands',
        imageUrl: 'https://i.ibb.co/Mhh6wBg/timberlands.png',
        price: 200,
      },
      {
        id: 111,
        name: 'New Balance 550',
        imageUrl: 'https://placehold.co/400x400/f0f0f0/222222?text=NB+550',
        price: 130,
      },
      {
        id: 112,
        name: 'Vans Old Skool',
        imageUrl: 'https://placehold.co/400x400/111111/ffffff?text=Vans+Old+Skool',
        price: 75,
      },
      {
        id: 113,
        name: 'Puma Suede Classic',
        imageUrl: 'https://placehold.co/400x400/7b2d26/ffffff?text=Puma+Suede',
        price: 85,
      },
      {
        id: 114,
        name: 'Nike Air Max',
        imageUrl: 'https://placehold.co/400x400/1f6feb/ffffff?text=Nike+Air+Max',
        price: 170,
      },
      {
        id: 115,
        name: 'Reebok Classic',
        imageUrl: 'https://placehold.co/400x400/eeeeee/222222?text=Reebok+Classic',
        price: 95,
        description: 'Timeless leather sneaker with a soft cushioned sole, built for everyday comfort.',
      },
      {
        id: 116,
        name: 'Converse Chuck 70',
        imageUrl: 'https://placehold.co/400x400/8c1f28/ffffff?text=Chuck+70',
        price: 90,
        description: 'Premium canvas high-top with vintage styling and extra cushioning underfoot.',
      },
      {
        id: 117,
        name: 'Asics Gel-Kayano',
        imageUrl: 'https://placehold.co/400x400/1f3f6f/ffffff?text=Asics+Gel',
        price: 160,
        description: 'Performance running shoe with gel cushioning for long-distance comfort.',
      },
      {
        id: 118,
        name: 'Yeezy Slide',
        imageUrl: 'https://placehold.co/400x400/9c9c9c/222222?text=Yeezy+Slide',
        price: 70,
        description: 'Minimalist slip-on slide with a molded EVA footbed for all-day wear.',
      },
      {
        id: 119,
        name: 'Nike Dunk Low',
        imageUrl: 'https://placehold.co/400x400/1a3a1a/ffffff?text=Dunk+Low',
        price: 115,
        description: 'Retro basketball-inspired sneaker with a low-cut silhouette and leather overlays.',
      },
    ],
  },
  {
    title: 'Jackets',
    items: [
      {
        id: 18,
        name: 'Black Jean Shearling',
        imageUrl: 'https://i.ibb.co/XzcwL5s/black-shearling.png',
        price: 125,
      },
      {
        id: 19,
        name: 'Blue Jean Jacket',
        imageUrl: 'https://i.ibb.co/mJS6vz0/blue-jean-jacket.png',
        price: 90,
      },
      {
        id: 20,
        name: 'Grey Jean Jacket',
        imageUrl: 'https://i.ibb.co/N71k1ML/grey-jean-jacket.png',
        price: 90,
      },
      {
        id: 21,
        name: 'Brown Shearling',
        imageUrl: 'https://i.ibb.co/s96FpdP/brown-shearling.png',
        price: 165,
      },
      {
        id: 22,
        name: 'Tan Trench',
        imageUrl: 'https://i.ibb.co/M6hHc3F/brown-trench.png',
        price: 185,
      },
      {
        id: 121,
        name: 'Black Bomber Jacket',
        imageUrl: 'https://placehold.co/400x400/141414/ffffff?text=Bomber+Jacket',
        price: 140,
      },
      {
        id: 122,
        name: 'Olive Utility Jacket',
        imageUrl: 'https://placehold.co/400x400/5a6b3f/ffffff?text=Utility+Jacket',
        price: 150,
      },
      {
        id: 123,
        name: 'Navy Pea Coat',
        imageUrl: 'https://placehold.co/400x400/1b2a4a/ffffff?text=Pea+Coat',
        price: 210,
      },
      {
        id: 124,
        name: 'Red Puffer Jacket',
        imageUrl: 'https://placehold.co/400x400/8c1f28/ffffff?text=Puffer+Jacket',
        price: 175,
      },
      {
        id: 125,
        name: 'Denim Trucker Jacket',
        imageUrl: 'https://placehold.co/400x400/3a5a78/ffffff?text=Trucker+Jacket',
        price: 95,
        description: 'Classic denim trucker jacket with button-front closure and chest pockets.',
      },
      {
        id: 126,
        name: 'Leather Moto Jacket',
        imageUrl: 'https://placehold.co/400x400/1a1a1a/ffffff?text=Moto+Jacket',
        price: 250,
        description: 'Asymmetric zip leather jacket with a slim fit for a bold, edgy look.',
      },
      {
        id: 127,
        name: 'Quilted Vest Jacket',
        imageUrl: 'https://placehold.co/400x400/4a3f35/ffffff?text=Quilted+Vest',
        price: 110,
        description: 'Lightweight quilted vest for layering, great for transitional weather.',
      },
      {
        id: 128,
        name: 'Windbreaker Jacket',
        imageUrl: 'https://placehold.co/400x400/2f6fa8/ffffff?text=Windbreaker',
        price: 80,
        description: 'Packable water-resistant windbreaker with a lightweight, breathable shell.',
      },
      {
        id: 129,
        name: 'Sherpa Fleece Jacket',
        imageUrl: 'https://placehold.co/400x400/8a7a5e/ffffff?text=Sherpa+Jacket',
        price: 120,
        description: 'Cozy sherpa fleece jacket, soft on the inside with a rugged corduroy collar.',
      },
    ],
  },
  {
    title: 'Womens',
    items: [
      {
        id: 23,
        name: 'Blue Tanktop',
        imageUrl: 'https://i.ibb.co/7CQVJNm/blue-tank.png',
        price: 25,
      },
      {
        id: 24,
        name: 'Floral Blouse',
        imageUrl: 'https://i.ibb.co/4W2DGKm/floral-blouse.png',
        price: 20,
      },
      {
        id: 25,
        name: 'Floral Dress',
        imageUrl: 'https://i.ibb.co/KV18Ysr/floral-skirt.png',
        price: 80,
      },
      {
        id: 26,
        name: 'Red Dots Dress',
        imageUrl: 'https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png',
        price: 80,
      },
      {
        id: 27,
        name: 'Striped Sweater',
        imageUrl: 'https://i.ibb.co/KmSkMbH/striped-sweater.png',
        price: 45,
      },
      {
        id: 28,
        name: 'Yellow Track Suit',
        imageUrl: 'https://i.ibb.co/v1cvwNf/yellow-track-suit.png',
        price: 135,
      },
      {
        id: 29,
        name: 'White Blouse',
        imageUrl: 'https://i.ibb.co/qBcrsJg/white-vest.png',
        price: 20,
      },
      {
        id: 131,
        name: 'Black Midi Skirt',
        imageUrl: 'https://placehold.co/400x400/1a1a1a/ffffff?text=Midi+Skirt',
        price: 40,
      },
      {
        id: 132,
        name: 'Beige Wide-Leg Trousers',
        imageUrl: 'https://placehold.co/400x400/d8c6a8/222222?text=Wide-Leg+Pants',
        price: 55,
      },
      {
        id: 133,
        name: 'Green Wrap Dress',
        imageUrl: 'https://placehold.co/400x400/3f6b4f/ffffff?text=Wrap+Dress',
        price: 85,
      },
      {
        id: 134,
        name: 'Denim Jacket',
        imageUrl: 'https://placehold.co/400x400/4a6f8a/ffffff?text=Denim+Jacket',
        price: 65,
      },
      {
        id: 135,
        name: 'Pink Knit Cardigan',
        imageUrl: 'https://placehold.co/400x400/e8a1b3/222222?text=Knit+Cardigan',
        price: 50,
        description: 'Soft button-front knit cardigan, perfect for layering over any outfit.',
      },
      {
        id: 136,
        name: 'High-Waist Jeans',
        imageUrl: 'https://placehold.co/400x400/3f5a7a/ffffff?text=High-Waist+Jeans',
        price: 60,
        description: 'Flattering high-waist skinny jeans with a comfortable stretch fit.',
      },
      {
        id: 137,
        name: 'Floral Maxi Dress',
        imageUrl: 'https://placehold.co/400x400/b06a8a/ffffff?text=Maxi+Dress',
        price: 90,
        description: 'Flowy floral-print maxi dress, ideal for summer outings and evening events.',
      },
      {
        id: 138,
        name: 'Off-Shoulder Top',
        imageUrl: 'https://placehold.co/400x400/c8a2c8/222222?text=Off-Shoulder+Top',
        price: 35,
        description: 'Elegant off-shoulder top with ruffled sleeves for a feminine silhouette.',
      },
      {
        id: 139,
        name: 'Leather Ankle Boots',
        imageUrl: 'https://placehold.co/400x400/3a2a1e/ffffff?text=Ankle+Boots',
        price: 95,
        description: 'Sleek leather ankle boots with a block heel, versatile for day or night.',
      },
    ],
  },
  {
    title: 'Mens',
    items: [
      {
        id: 30,
        name: 'Camo Down Vest',
        imageUrl: 'https://i.ibb.co/xJS0T3Y/camo-vest.png',
        price: 325,
      },
      {
        id: 31,
        name: 'Floral T-shirt',
        imageUrl: 'https://i.ibb.co/qMQ75QZ/floral-shirt.png',
        price: 20,
      },
      {
        id: 32,
        name: 'Black & White Longsleeve',
        imageUrl: 'https://i.ibb.co/55z32tw/long-sleeve.png',
        price: 25,
      },
      {
        id: 33,
        name: 'Pink T-shirt',
        imageUrl: 'https://i.ibb.co/RvwnBL8/pink-shirt.png',
        price: 25,
      },
      {
        id: 34,
        name: 'Jean Long Sleeve',
        imageUrl: 'https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png',
        price: 40,
      },
      {
        id: 35,
        name: 'Burgundy T-shirt',
        imageUrl: 'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
        price: 25,
      },
      {
        id: 141,
        name: 'Grey Hoodie',
        imageUrl: 'https://placehold.co/400x400/5c5c5c/ffffff?text=Grey+Hoodie',
        price: 45,
      },
      {
        id: 142,
        name: 'Navy Chinos',
        imageUrl: 'https://placehold.co/400x400/1c2b4a/ffffff?text=Navy+Chinos',
        price: 55,
      },
      {
        id: 143,
        name: 'Black Bomber',
        imageUrl: 'https://placehold.co/400x400/111111/ffffff?text=Black+Bomber',
        price: 130,
      },
      {
        id: 144,
        name: 'Striped Polo',
        imageUrl: 'https://placehold.co/400x400/2f6f5e/ffffff?text=Striped+Polo',
        price: 30,
      },
      {
        id: 145,
        name: 'Denim Jacket',
        imageUrl: 'https://placehold.co/400x400/3a5a78/ffffff?text=Denim+Jacket',
        price: 90,
        description: 'Rugged denim jacket with a classic collar and button-flap chest pockets.',
      },
      {
        id: 146,
        name: 'Slim Fit Blazer',
        imageUrl: 'https://placehold.co/400x400/1c1c2e/ffffff?text=Slim+Blazer',
        price: 150,
        description: 'Tailored slim-fit blazer for a sharp, polished look at work or events.',
      },
      {
        id: 147,
        name: 'Cargo Joggers',
        imageUrl: 'https://placehold.co/400x400/4a5a3f/ffffff?text=Cargo+Joggers',
        price: 48,
        description: 'Comfortable tapered joggers with multiple utility pockets.',
      },
      {
        id: 148,
        name: 'Flannel Shirt',
        imageUrl: 'https://placehold.co/400x400/7a2f2f/ffffff?text=Flannel+Shirt',
        price: 38,
        description: 'Soft brushed-cotton flannel shirt in a classic plaid pattern.',
      },
      {
        id: 149,
        name: 'Crew Neck Sweater',
        imageUrl: 'https://placehold.co/400x400/5a5a5a/ffffff?text=Crew+Sweater',
        price: 42,
        description: 'Ribbed crew-neck sweater made from a warm cotton-wool blend.',
      },
    ],
  },
];

export default SHOP_DATA;